spring:
  datasource:
    url: jdbc:mysql://1.14.140.53:3306/imooc-security-demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: jh541224
    driver-class-name: com.mysql.jdbc.Driver
  #    暂时关闭session配置m
  session:
    store-type: redis
  redis:
    host: 1.14.140.53
    port: 6379
security:
#  basic:
#    enabled: false
  oauth2:
    client:
      clientId: imooc
      clientSecret: imoocsecret
swagger:
  enable: true